spring:
  docker:
    compose:
      file: docker/docker-compose.yml
  banner:
    location: classpath:banner.txt
  application:
    name: pismoTestCase
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/postgres?createDatabaseIfNotExist=true
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:123}
    driver-class-name: org.postgresql.Driver # Explicitly declare the driver class name
    hikari:
      maximum-pool-size: ${HIKARI_POOL_SIZE:2}
  jpa:
    generate-ddl: false
    show-sql: true
    properties.hibernate.format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000